name: Send Reminder Emails

on:
  push:
    branches:
      - setup-mailer

  schedule:
    # This cron syntax runs the workflow every 5 minutes.
    - cron: '*/5 * * * *' 

jobs:
  send_reminders:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt  # Ensure all your dependencies are listed here
      
      - name: Run reminder checker
        run: |
          python check_reminders.py
